#DROPANDO SCHEMA CRIADO
#DROP SCHEMA CONTROLE_ESTOQUE;

#CRIANDO SCHEMA
CREATE SCHEMA CONTROLE_ESTOQUE;

#USAR O SCHEMA
USE CONTROLE_ESTOQUE;

#CRIANDO TABELAS
CREATE TABLE PRODUTO(
ID_PROD		INT 						NOT NULL AUTO_INCREMENT,
NOME_PROD		VARCHAR(40)				NOT NULL,
COD_BARRA	INT				UNIQUE		NOT NULL,
LOTE		SMALLINT					NOT NULL,
VALOR		float						NOT NULL,
QUANTIDADE	INT							NOT NULL,
	CONSTRAINT PK_ID_PROD
		PRIMARY KEY (ID_PROD)
);

CREATE TABLE SETOR(
ID_SET		INT 			NOT	NULL,
NOME_SET	VARCHAR(40)		NOT NULL
);

#VERIFICAR O ID NAO CONFERE AO SETOR

CREATE TABLE SAIDA(
ID_SAIDA	INT		NOT NULL AUTO_INCREMENT,
ID_PROD		INT,
ID_SET		INT,
	CONSTRAINT PK_ID_SAIDA
		PRIMARY KEY(ID_SAIDA),
	CONSTRAINT FK1_SAIDA_SETOR
		FOREIGN KEY(ID_SET)
        REFERENCES SETOR(ID_SET),
	CONSTRAINT FK2_SAIDA_PRODUTO
		FOREIGN KEY(ID_PROD)
        REFERENCES PRODUTO(ID_PROD)
);

